### ISSUE TITLE
Empty notes deleted forever

### ISSUE THREAD

**Issue by Dragonfly-30** [PhilKes/NotallyX#118] opened 2024-11-07 04:03 UTC
Thank you for implementing auto-deletion for empty notes, it works as intended. However, Empty notes still move to the 'Deleted' section instead of being permanently removed. It seems more intuitive for an empty note to delete itself permanently rather than going to the trash.

**Comment by PhilKes** [comment] 2024-11-07 16:38
I cant reproduce this, how exactly did you test this and on what app version?

[notallyx_issues_118.webm](https://github.com/user-attachments/assets/dbb0ea0b-c0ff-438d-84a6-f50b4c48abc9)

**Comment by PhilKes** [comment] 2024-12-01 12:53
Since I believe this is already fixed and to keep things organized, I am going to close this.
If the problem re-occurs, feel free to open another issue 😄

**Closed by PhilKes** 2024-12-01 12:53 UTC
Labels: enhancement

**Comment by Dragonfly-30** [comment] 2024-12-02 19:42
So sorry for not replying sooner, I did saw your reply and thought of replying later but forgot about it. I tested this again on version 6.2 and the issue seems to be resolved. Thank you very much.
